<?php
// $Id$

/**
* @file
* Hides the sku input field on the edit product form
* and allocates its default value with 'default'.
*/

/**
* Implementation of hook_form_alter().
*/
function uc_nosku_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "product_node_form") {
      $form['base']['model']['#default_value'] = 'default';
      $form['base']['model']['#type'] = 'hidden';
	   $form['base']['prices']['#type'] = 'hidden';
	  $form['base']['prices']['list_price']['#type'] = 'hidden';
	  $form['base']['prices']['cost']['#type'] = 'hidden';
  }
}